apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns

spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
        - args:
            - --source=ingress
            - --source=service
            - --domain-filter=games.automateit.ca
            - --provider=google
            - --google-project="notr-2022-anthos-364917"
            - --registry=txt
            - --txt-owner-id="agones-gcp-cluster"
          image: k8s.gcr.io/external-dns/external-dns:v0.8.0
          name: external-dns
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
      serviceAccountName:  external-dns-sa-gcp