apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
  annotations: 
      configsync.gke.io/cluster-name-selector: agnones-azure-cluster		
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
        - args:
            - --txt-owner-id="agnones-azure-cluster"
      serviceAccountName:  external-dns-sa-azure