namespace: external-dns

resources:
- ../../base/external-dns

patches:
- path: serviceaccount-patch.yaml
  target:
    kind: ServiceAccount
- path: deployment-patch.yaml
  target:
    kind: Deployment
- path: clusterrolebinding-patch.yaml
  target:
    kind: ClusterRoleBinding
- path: fleet-patch.yaml
  target: 
    kind: Fleet
nameSuffix:
  -aks

commonAnnotations: 
      configsync.gke.io/cluster-name-selector: agnones-aks-cluster	